### ISSUE TITLE
new version in europe (france at least)

### ISSUE THREAD

**Issue by pkshetlie** [elmedico27/fordpowerup#11]
6.4.0, it looks to be the same description as your table.

we also get a 24/23-PU update but can't remember which one

**Comment by DekkersR** [comment]
Just got '24-PU0102-SVD-FX' here in The Netherlands (EU)

**Comment by elmedico27** [comment]
Thank you both!  I've marked 6.4.0 and SVD-FX as available in EU as of Feb 2024
