### ISSUE TITLE
24-PU0102-SVD-FX /6.4.0 available in Uk

### ISSUE THREAD

**Issue by mikemurk** [elmedico27/fordpowerup#13]
Hey, 

So 24-PU0102-SVD-FX was pushed to my job one mach-e yesterday, overnight. Release notes the same as US. And the 6.4.0 was pushed today, release notes the same as US, and it was non-drivable for 10 minutes.

Ta

**Comment by elmedico27** [comment]
Fantastic, thank you!  Especially for the non-drivable time, looks like EU is a bit different, so I will specify that.
