### ISSUE TITLE
24-PU0119-DC-CHG4

### ISSUE THREAD

**Issue by 360alaska** [elmedico27/fordpowerup#16]
Priority Update - Tesla Supercharger Network
Plug & Charge at Tesla Superchargers
This update will allow you to use Ford's Plug & Charge services at thousands of Tesla Superchargers.* Simply plug in. Charging starts automatically and is billed to your credit card on file.
To do so you will need to:
. Be enrolled in the BlueOvalTM Charge Network.
• Get a Fast Charging Adapter, available from Ford.
Reserve your Fast Charging Adapter and learn more at Ford.com/
FastChargingAdapter
Software updates are designed to help make your vehicle better over time.
*Available in US and Canada only.
24-PU0119-DC-CHG4

**Comment by elmedico27** [comment]
Added!  Thanks!
