### ISSUE TITLE
new upgrade in France (Europe) 24-PU0102-CHG-SUFX

### ISSUE THREAD

**Issue by pkshetlie** [elmedico27/fordpowerup#19]
Hi, new update two days ago
translated by google translation : 

WHAT’S IN THIS UPDATE?

Software update

Improvements related to charging.

- Fast DC charging

When you head towards a fast charging station (guidance initiated via the on-board navigation system), battery preconditioning* will start in the last 30 kilometers before your arrival at the charging station.

This will allow your battery to accept a faster charging speed, especially in cold weather.

- Battery life displayed

The range displayed has been adjusted to reflect what is possible under optimal driving conditions.

- Vehicle charging port

The range displayed has been adjusted to reflect what is possible under optimal driving conditions.

Software updates are designed to improve your vehicle over time.

Priority Update 24-PU0102-CHG-SUFX

**Comment by elmedico27** [comment]
Added - thank you!
