### ISSUE TITLE
New Mustang Mach-E update available (EA) - 24-PU1024-6CH-AUD

### ISSUE THREAD

**Issue by dougnet** [elmedico27/fordpowerup#20]
24-PU1024-6CH-AUD Priority Update - Audio - Refined Audio
![355C5F2C-4EC7-44A2-AEE0-928829E01334_1_105_c](https://github.com/elmedico27/fordpowerup/assets/40474578/29804bb6-b6c8-4fe4-9a4a-8ce60aa4a5df)

Looks like a 7 minute inhibit.

**Comment by elmedico27** [comment]
Thank you, sir!

**Comment by jmgreen67** [comment]
Maybe you could change the title, as this is not the **24**-PU1024-6CH-AUD but the **23**-PU1024-6CH-AUD

**Comment by pkshetlie** [comment]
The same in France (Eu)
