### ISSUE TITLE
BC 1.3 OTA also updates PSCM

### ISSUE THREAD

**Issue by AvdonR** [elmedico27/fordpowerup#25]
The Bluecruise 1.3 OTA also updates the PSCM module as well as the IPMA even though the OTA label just says IPMA. New reported version on FDRS/PTS is LJ9C-14D003-GA. Attached screenshot is a vehicle coming from Bluecruise 1.0.

<img width="1059" alt="image" src="https://github.com/user-attachments/assets/0ff5bb74-f286-417c-9aac-75146e09b6e5">

**Comment by elmedico27** [comment]
Thanks for submitting and bringing this up.  I'm working with some folks on the forums to look into this one, I need more info on when PSCM is/is not included in the OTA (doesn't seem to be 100%).  Gonna leave this one open for a bit, for tracking.

**Comment by elmedico27** [comment]
I went ahead and added that the PSCM is also updated sometimes - never got a solid answer, but since you've seen it, I'll include it.  Thank you!
