### ISSUE TITLE
24-PU0301-BLM-PE In EU

### ISSUE THREAD

**Issue by fflaten** [elmedico27/fordpowerup#28]
Priority Update 24-PU0301-BLM-PE seen today for MME MY2023. Norway. 

![image](https://github.com/user-attachments/assets/617029ef-b531-4d84-afb6-c272936d92f3)

**Comment by elmedico27** [comment]
Added, thanks!

**Comment by fflaten** [comment]
Thanks. You forgot to add the EU release date.

**Comment by elmedico27** [comment]
Whoops, good catch, fixed
