### ISSUE TITLE
4.2.1.2 - Released in UK

### ISSUE THREAD

**Issue by mikemurk** [elmedico27/fordpowerup#3]
Hi Received 4.2.1.2 in the UK on a Job 1 ER AWD Mach E

![Screenshot (11 Aug 2023 15_21_06)](https://github.com/elmedico27/fordpowerup/assets/26260976/581907ce-9d4d-4435-a789-2aec21452c9d)

Release notes:  

Ford Power-Up 4.2.1.2

Smart Changes.

Minor Background updates have been made.  You will not notice any difference, but these refinements will set you up for future updates to come.

Ford Power-Up delivers software updates that are designed to make your Mustang Mach-E electric vehicle better over time.

**Comment by pkshetlie** [comment]
same in France yesterday :D

**Comment by andersthorsen** [comment]
Same in Norway a few days ago.

![image](https://github.com/elmedico27/fordpowerup/assets/190081/27622c3d-dd71-4fc8-b237-e7cf8af5c5cc)

About says Ford sync is at 23095 rev 807

**Comment by elmedico27** [comment]
This has been added -- thanks for including the release notes!
