### ISSUE TITLE
6.14.0 in EU

### ISSUE THREAD

**Issue by fflaten** [elmedico27/fordpowerup#37]
Seen on MME '23 today. Release note headlines video streaming, in addition to the published list with display brightness ++

**Comment by elmedico27** [comment]
Thanks!  I've marked that it's available - do you happen to have the full release notes for me to add in?

**Comment by fflaten** [comment]
![image](https://github.com/user-attachments/assets/ceafe79d-34e1-42e6-86dc-5ea368e7413f)
