### ISSUE TITLE
5.1.1 Release Europe

### ISSUE THREAD

**Issue by martinostvik** [elmedico27/fordpowerup#4]
Received update for v5.1.1 in Norway September 30th 2023.
![image](https://github.com/elmedico27/fordpowerup/assets/57357767/385cacf3-3518-4a04-afb6-0bcefa2f9e28)

Release note in Norwegian does not mention anything about preconditioning battery before arriving at charging stations if using the built in navigation.

**Comment by elmedico27** [comment]
Thanks!  Updated in commit [fd47986](https://github.com/elmedico27/fordpowerup/commit/fd47986fa0d1d52574e0266a86a91f7e557ed1f6)
