### ISSUE TITLE
New update today in France (Europe)

### ISSUE THREAD

**Issue by pkshetlie** [elmedico27/fordpowerup#5]
![Screenshot_2023-10-27-09-03-47-12_4ad881d1d915822054ab110b5242e902](https://github.com/elmedico27/fordpowerup/assets/266652/00202776-81b6-4fc8-9dac-7db59d990afd)

**Comment by elmedico27** [comment]
Thank you!  I added this version to the main page.  I don't speak French and my text extractor didn't want to play nice with all the accent marks, so I didn't bring in many of the release notes.  If you have a way to get them in text, all on one line, I'm happy to paste in here.
