### ISSUE TITLE
Ford Power-Up 6.1.0 in The Netherlands

### ISSUE THREAD

**Issue by jacuytdehaag** [elmedico27/fordpowerup#8]
received the 6.1.0 update on November 6th 2023.

![ford_powerup_6 1 0_netherlands](https://github.com/elmedico27/fordpowerup/assets/151090225/a219797e-9ac6-4ff7-9b79-7616c0ed33cc)

**Comment by ptemmer** [comment]
En ik die dacht dat we in Europa niet verder waren geraakt dan de 4.1.2 update....blijkbaar niet.
Hoe loopt de wagen @jacuytdehaag ?

**Comment by jacuytdehaag** [comment]
End of October the MME received 5.1.1 and shortly after that 6.1.0. 
I hope we will get the highest version of the software soon. 
Ford has announced the BlueCruise will become available in Europe:
https://media.ford.com/content/fordmedia/fna/us/en/news/2023/10/06/ford-expands-europe-hands-free-driving-availability-with-bluecru.html
And hopefully it will also be available soon in the Netherlands as well:
https://topgear.nl/autonieuws/zelfstandig-rijdende-auto-nederland-ford-mustang-mach-e/

@ptemmer wagen rijdt nog fantastisch. Nog steeds dik tevreden over de auto na ca 1 jaar en 22.000 km.

**Comment by elmedico27** [comment]
Thank you!  I have marked that 6.1.0 is available in Europe.
