### ISSUE TITLE
New update in France 

### ISSUE THREAD

**Issue by pkshetlie** [elmedico27/fordpowerup#9]
![Screenshot_2023-11-25-00-09-57-90_4ad881d1d915822054ab110b5242e902](https://github.com/elmedico27/fordpowerup/assets/266652/14a179bc-1eae-4bc5-a5a7-7dc932ca89d8)

 SOFTWARE UPDATES

 SUCCESSFUL UPDATE

 Received Nov. 24, 2023

 Check out what's new!  Ford Power-Up software updates like this enhance the quality, capability and convenience of the vehicle.

 WHAT’S IN THIS UPDATE?

 Ford Power-Up 6.3.0

 Improvements and fixes This update brings optimization of vehicle connectivity (FordPass Connect) as well as adjustments and fixes to the system for better stability.

 Ford Power-Up Updates are designed to give you a permanent upgrade to your Mustang Mach-E over time.

**Comment by elmedico27** [comment]
Excellent, thank you for the update!
